try:
    list = [1, 2, 3]
    print(list[5])
except Exception as exception:
    print('에러가 발생했습니다.')
    print(exception)
